# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Atool < Formula
  desc ""
  homepage ""
  url "https://github.com/minus5/tmp/releases/download/v0.1.5/tmp_0.1.5_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "0.1.5"
  sha256 "d67c825b6135efe1c43c3b2d716efcf3510c6c0f57d1ea04f5146fabfc0b6741"

  def install
    bin.install "tmp"
  end
end
