# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Atool < Formula
  desc ""
  homepage ""
  url "https://github.com/minus5/tmp/releases/download/v0.1.6/btool_0.1.6_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "0.1.6"
  sha256 "5f258630928682d0e7e2f218594f490a096de148766f93f9af77d6e7ef4b5bfb"

  def install
    bin.install "btool"
  end
end
