# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Btool < Formula
  desc ""
  homepage ""
  url "https://github.com/minus5/tmp/releases/download/v0.1.7/btool_0.1.7_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "0.1.7"
  sha256 "34e61a60906406de425f0fded7ce22e34d7de9302a7a12a06be0957f43acdf38"

  def install
    bin.install "btool"
  end
end
