# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Pitwall < Formula
  desc ""
  homepage ""
  url "https://github.com/minus5/tmp/releases/download/v1.0.0/pitwall_1.0.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "1.0.0"
  sha256 "894f1220e0f4959432160f59b1223ba54660c95aeffb69509a0825b3e3b936a3"

  def install
    bin.install "pitwall"
  end
end
